#ifndef CALIBRATEINFORMATIONMEASURE_GLOBAL_H
#define CALIBRATEINFORMATIONMEASURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALIBRATEINFORMATIONMEASURE_LIBRARY)
#  define CALIBRATEINFORMATIONMEASURESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CALIBRATEINFORMATIONMEASURESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CALIBRATEINFORMATIONMEASURE_GLOBAL_H
