#ifndef CVFEATUREEXTRACTMATCH_GLOBAL_H
#define CVFEATUREEXTRACTMATCH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CVFEATUREEXTRACTMATCH_LIBRARY)
#  define CVFEATUREEXTRACTMATCHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CVFEATUREEXTRACTMATCHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CVFEATUREEXTRACTMATCH_GLOBAL_H
